apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carrier-net-ca-tools
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: carrier-net-ca-tools
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/catools
  values:
    metadata:
      namespace: carrier-net
      name: ca-tools
      component_type: peer
      org_name: carrier
      proxy: none
    replicaCount: 1

    image:
      repository: hyperledger/fabric-ca-tools
      tag: 1.2.1
      pullPolicy: IfNotPresent
      alpineutils: ghcr.io/hyperledger/alpine-utils:1.0
      
    storage:
      storageclassname: carriersc
      storagesize: 512Mi
    
    vault:
      role: vault-role
      address: http://35.231.244.169:8200
      authpath: localcarrier-net-auth
      secretusers: secretsv2/data/crypto/peerOrganizations/carrier-net/users
      secretorderer: secretsv2/data/crypto/peerOrganizations/carrier-net/orderers
      secretpeer: secretsv2/data/crypto/peerOrganizations/carrier-net/peers
      secretpeerorderertls: secretsv2/data/crypto/peerOrganizations/carrier-net/orderer/tls
      secretambassador: secretsv2/data/crypto/peerOrganizations/carrier-net/ambassador
      secretcert: secretsv2/data/crypto/peerOrganizations/carrier-net/ca?ca.carrier-net-cert.pem
      secretkey: secretsv2/data/crypto/peerOrganizations/carrier-net/ca?carrier-net-CA.key
      secretcouchdb: secretsv2/data/credentials/carrier-net/couchdb/carrier
      secretconfigfile: secretsv2/data/crypto/peerOrganizations/carrier-net/msp/config
      serviceaccountname: vault-auth
      imagesecretname: regcred
    
    healthcheck: 
      retries: 10
      sleepTimeAfterError: 2

    
    org_data:
      external_url_suffix: develop.local.com
      component_subject: O=Carrier,OU=Carrier,L=51.50/-0.13/London,C=GB
      cert_subject: O=Carrier/OU=Carrier/L=51.50,-0.13,London/C=GB
      component_country: GB
      component_state: London
      component_location: London
      ca_url: ca.carrier-net:7054

    orderers:
      name: orderer1-
    orderers_info:
      - name: orderer1
        path: "certs/orderer1-ca.crt"

    peers:
      name: peer0,-      
    peer_count: "1"
    users: 
      users_list: "W3sndXNlcic6IE5vbmUsICdpZGVudGl0eSc6ICd1c2VyMScsICdhdHRyaWJ1dGVzJzogW3sna2V5JzogJ2hmLlJldm9rZXInLCAndmFsdWUnOiAndHJ1ZSd9XX1d"
      users_identities: user1-
    checks:
      refresh_cert_value: False
      add_peer_value: False
