apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: manufacturer-net-ca-tools
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: manufacturer-net-ca-tools
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/catools
  values:
    metadata:
      namespace: manufacturer-net
      name: ca-tools
      component_type: peer
      org_name: manufacturer
      proxy: none
    replicaCount: 1

    image:
      repository: hyperledger/fabric-ca-tools
      tag: 1.2.1
      pullPolicy: IfNotPresent
      alpineutils: ghcr.io/hyperledger/alpine-utils:1.0
      
    storage:
      storageclassname: manufacturersc
      storagesize: 512Mi
    
    vault:
      role: vault-role
      address: http://35.185.39.110:8200
      authpath: localmanufacturer-net-auth
      secretusers: secretsv2/data/crypto/peerOrganizations/manufacturer-net/users
      secretorderer: secretsv2/data/crypto/peerOrganizations/manufacturer-net/orderers
      secretpeer: secretsv2/data/crypto/peerOrganizations/manufacturer-net/peers
      secretpeerorderertls: secretsv2/data/crypto/peerOrganizations/manufacturer-net/orderer/tls
      secretambassador: secretsv2/data/crypto/peerOrganizations/manufacturer-net/ambassador
      secretcert: secretsv2/data/crypto/peerOrganizations/manufacturer-net/ca?ca.manufacturer-net-cert.pem
      secretkey: secretsv2/data/crypto/peerOrganizations/manufacturer-net/ca?manufacturer-net-CA.key
      secretcouchdb: secretsv2/data/credentials/manufacturer-net/couchdb/manufacturer
      secretconfigfile: secretsv2/data/crypto/peerOrganizations/manufacturer-net/msp/config
      serviceaccountname: vault-auth
      imagesecretname: regcred
    
    healthcheck: 
      retries: 10
      sleepTimeAfterError: 2

    
    org_data:
      external_url_suffix: develop.local.com
      component_subject: O=Manufacturer,OU=Manufacturer,L=47.38/8.54/Zurich,C=CH
      cert_subject: O=Manufacturer/OU=Manufacturer/L=47.38,8.54,Zurich/C=CH
      component_country: CH
      component_state: Zurich
      component_location: Zurich
      ca_url: ca.manufacturer-net:7054

    orderers:
      name: orderer1-
    orderers_info:
      - name: orderer1
        path: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBRENDQWFhZ0F3SUJBZ0lVT20wbitaemk1SlRtVDl3SmhQaXFoalc2dm9zd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TmpJd01UWXpOelEyV2hjTk1qWXdOREE1TVRZek56UTJXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJCbndvdmcvY1IyVjAzWWNsdFpWU243c2w3ME1SeEgrZTNOT3BESk4zNmhheTV3NzduQTgKb1hhNUlxazJBQmtLTGJWLzVobzFzdE95aDZTVzE2VzAyYm1qUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU1pjeHdmaHpCRWFFeUZZejUvTlNOMmN2bGJRakFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQXdxdStNQUpHUXZpRGNQVEFMaW9pMlRUMnNmM29uRDJmVzBLTmlEYlUKZSswQ0lHaHp6WDNHR2o4WCtXK01qV2xKdXcyMVdIQ0RHQlJ3Z0hxZ1orRm13ZG9wCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0="

    peers:
      name: peer0,-      
    peer_count: "1"
    users: 
      users_list: "W3sndXNlcic6IE5vbmUsICdpZGVudGl0eSc6ICd1c2VyMScsICdhdHRyaWJ1dGVzJzogW3sna2V5JzogJ2hmLlJldm9rZXInLCAndmFsdWUnOiAndHJ1ZSd9XX1d"
      users_identities: user1-
    checks:
      refresh_cert_value: False
      add_peer_value: False
